import { Content } from "@/april28_23/components/layout/layout";
import { Card } from "@/april28_23/domainComponents/card/card";
import { Slider } from "@/april28_23/domainComponents/slider/slider";
import { Inter } from "next/font/google";
import Head from "next/head";

const interFont = Inter({ subsets: ["latin"], variable: "--inter-font" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Daily Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </Head>
      <Content>
        <div>
          <a className="text-white" href="https://dribbble.com/shots/21320120-Banking-App">
            https://dribbble.com/shots/21320120-Banking-App
          </a>
          <Card
            displayType="secondary"
            mask={4765111122225674}
            expiration={"03/25"}
            balance={3201.34}
            cardType={"mastercard"}
            bankName={"World Bank"}
          />
          <Card
            displayType="primary"
            mask={3456111122222234}
            expiration={"04/28"}
            balance={2156.09}
            cardType={"visa"}
            bankName={"Country Bank"}
          />
        </div>
        <Slider />
      </Content>
    </>
  );
}
